### ISSUE TITLE
Use settings value instead of BaseURL model

### ISSUE THREAD

**Issue by kvbik** [efdevcon/pretix-attestation-placeholder-plugin#30]
There is a DB value specific for this plugin called `BaseURL`. If it is just the URL where the Pretix instance is running, this value should be define in Django settings (`from django.conf import settings`) and is called `settings.SITE_URL`.

**Comment by ligi** [comment]
no - it could be a different site - so IMHO this is correct so - the attestation site will most likely not be part of the pretix instance but part of the website.

**Comment by kvbik** [comment]
Gotcha @ligi - It crossed my mind this can be the way it works. Thank you - closing!
