### ISSUE TITLE
Plugin shows up in wrong category

### ISSUE THREAD

**Issue by ligi** [efdevcon/pretix-attestation-placeholder-plugin#9]
It's not a payment plugin - maybe in output or other (@raphaelm any input on where a placeholder should live in @pretix ?)

![Selection_415](https://user-images.githubusercontent.com/111600/105029272-69932080-5a52-11eb-9344-fac13f5456a7.png)

**Comment by raphaelm** [comment]
:man_shrugging: not really. Customizations or other, probably

**Comment by ligi** [comment]
closed by #11
